name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Compiler CodeQuality
        run: dotnet build Tools/CodeQuality/CodeQuality.csproj

      - name: Exécuter CodeQuality
        run: dotnet run --project Tools/CodeQuality/CodeQuality.csproj